name: CI Pipeline

on:  
  push:
  pull_request:

jobs:
  test-node:
    name: Test Node.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  # Faster and cleaner than "npm install"

      - name: Fix Jest Permission Issue
        run: chmod +x node_modules/.bin/jest  # Fix jest permission

      - name: Run tests
        run: npm test
        
      - name: Run a test
        run: |
          echo "Running on my custom runner!"
          echo "Host: $HOSTNAME"
          pwd
